# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colSumByFac <- function(sY, rowSel) {
    .Call('_swne_colSumByFac', PACKAGE = 'swne', sY, rowSel)
}

colMeanVarS <- function(sY, rowSel) {
    .Call('_swne_colMeanVarS', PACKAGE = 'swne', sY, rowSel)
}

inplaceWinsorizeSparseCols <- function(sY, n) {
    .Call('_swne_inplaceWinsorizeSparseCols', PACKAGE = 'swne', sY, n)
}

ComputeSNN <- function(nn_ranked, prune) {
    .Call('_swne_ComputeSNN', PACKAGE = 'swne', nn_ranked, prune)
}

pnorm_over_mat <- function(R_num_links_ij, R_var_null_num_links) {
    .Call('_swne_pnorm_over_mat', PACKAGE = 'swne', R_num_links_ij, R_var_null_num_links)
}

